hero:
  greeting: "Hi! I'm Pat"
  emoji: "👋"
  title: "A tinkerer, data nerd, and lifelong learner."
  blurb: "I write about open data, digital policy, and try to share useful tidbits for open data producers and consumers."
  cta_primary: "Read the Blog"
  cta_primary_link: "#latest"
  cta_secondary: "View Resume"
  cta_secondary_link: "/resume/"
  image_alt: "Workspace with laptop, sketches, and coffee"
  image: "/assets/images/hero-illustration.svg"
profile:
  name: "Pat Little"
  role: "Dude Doing Data and Analytics"
  bio: "Opening the Open Data, Trying to enable others, Learning along the way."
  avatar: "/assets/images/avatar-head.png"
sections:
  highlights_title: "Projects in Progress"
  highlights:
    - title: "Skateway Data"
      image: "https://github.com/user-attachments/assets/c612a154-81ea-4459-85e1-0c3d032a2a70"
      link: "https://github.com/PatLittle/skateway_data"
    - title: "TBS Policy Hawk"
      image: "https://github.com/user-attachments/assets/2cade396-76a8-474a-8c17-f0f7ed1e69ab"
      link: "https://github.com/PatLittle/TBS-Policy-Hawk"
    - title: "Consultations Tracker"
      image: "/assets/images/highlight-3.svg"
      link: "https://patlittle.github.io/Consultations-Tracker/report.html"
    - title: "GC-Ref-Data-Tracker"
      image: "/assets/images/highlight-4.svg"
      link: "https://patlittle.github.io/GC-Ref-Data-Tracker/index.html"
  topics_title: "Topics"
  topics:
    - "Data Products"
    - "AI"
    - "Development & Systems"
    - "Travel / Personal"
social:
  github:
    label: "GitHub"
    url: "https://github.com/PatLittle"
  linkedin:
    label: "LinkedIn"
    url: "https://www.linkedin.com/in/patrickjlittle/"
rss:
  label: "RSS"
  url: "/feed.xml"
