hero:
  greeting: "Hi! I'm Pat"
  emoji: "👋"
  title: "A digital builder, product nerd, and lifelong learner."
  blurb: "I write about building high-trust teams, designing thoughtful products, and shipping software that helps people do their best work."
  cta_primary: "Read the Blog"
  cta_primary_link: "#latest"
  cta_secondary: "View Resume"
  cta_secondary_link: "/resume/"
  image_alt: "Workspace with laptop, sketches, and coffee"
  image: "/assets/images/hero-illustration.svg"
profile:
  name: "Pat Little"
  role: "Product & Engineering Leader"
  bio: "I help teams ship delightful software with clarity, curiosity, and care."
  avatar: "/assets/images/avatar.svg"
sections:
  highlights_title: "Nerd Stuff"
  highlights:
    - title: "Product Strategy"
      image: "/assets/images/highlight-1.svg"
    - title: "Developer Experience"
      image: "/assets/images/highlight-2.svg"
    - title: "AI & Automation"
      image: "/assets/images/highlight-3.svg"
    - title: "Design Systems"
      image: "/assets/images/highlight-4.svg"
  newsletter_title: "Stay inspired weekly ✨"
  newsletter_body: "A short email on lessons learned, what I'm reading, and tools worth sharing. No spam, ever."
  topics_title: "Topics"
  topics:
    - "Product"
    - "Engineering"
    - "Leadership"
    - "Creativity"
    - "Career"
    - "AI"
    - "Systems"
    - "Writing"
