name: Update index.html with GitHub Repos

on:
  schedule:
    - cron: '0 0-12 * * *'
  workflow_dispatch:

jobs:
  update-page:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate repos list
      run: python generate_repos_list.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.html
        git commit --allow-empty -m 'Update index.html with latest GitHub repos'
        git push


